name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq /
        sudo apt-get install libsdl2-dev
      
    - name: Build
      run: make
      
    - name: Run distcheck
      run: make distcheck
